from rest_framework import status
from ..serializer import (AddItemSerializer)

def Inventory_AddItem(data):
    """
    Function to add new items in inventory.

    Args:
        data ([json]): ['ItemName', 'ItemLocation']

    Returns:
        [
            return_value: message and status generated by the request.
            status_code: status of the request.
        ]
    """
    try:
        serializer = AddItemSerializer(data=data)
        if(serializer.is_valid()):
            serializer.save()

            status_code=status.HTTP_200_OK
            return_value={'message':"record saved succesfully",
                                'status':True}   
            return return_value, status_code                                             
        else:
            status_code=status.HTTP_400_BAD_REQUEST
            return_value={'message':"Error in saving record",
                        'status':False}
            return return_value, status_code                                             
    except :
            status_code=status.HTTP_400_BAD_REQUEST
            return_value={'message':"Error in saving record",
                        'status':False}
            return return_value, status_code                                             
