# Generated by Django 3.2.11 on 2022-01-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDB',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.TextField(max_length=20)),
                ('ItemLocation', models.TextField(max_length=20)),
                ('DeleteComment', models.TextField(max_length=200)),
                ('DeleteStatus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'InventoryDB',
            },
        ),
    ]
